# Generated by Django 3.1.1 on 2020-10-07 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=300)),
                ('question_html', models.TextField()),
                ('optiona', models.TextField(max_length=100)),
                ('optionb', models.TextField(max_length=100)),
                ('optionc', models.TextField(max_length=100)),
                ('optiond', models.TextField(max_length=100)),
                ('answer', models.TextField(max_length=100)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('logical', 'Logical')], default='Technical', max_length=20)),
            ],
            options={
                'ordering': ('-category',),
            },
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalMarks', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
