# Generated by Django 3.1.1 on 2020-10-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('aptitude', 'aptitude')], default='Technical', max_length=20),
        ),
    ]
